name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Zip extension files
        uses: montudor/action-zip@v1

      - name: Zip files
        run: zip -qq -r extension.zip contentScript.js favicon.png icon.png manifest.json

      - name: Upload & release
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: extension.zip
          extension-id: hogefuga(lflnlpdbgadmglldnjiipneepfagajfh)
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
